export const wishlist = {
    "data":
    [
        {
            "storeId":1,
            "category":"surfing",
            "title":"카약 함덕점",
            "content":"소개글 내용입니다1",
            "address": "제주시 제주도 제주읍",
            "rating": 4.5,
            "reviewCount": 12,
            "price":5000,
            "isLike":true,
            "storeImage": "https://i.pinimg.com/564x/49/d5/0d/49d50dd7b84fcfc4833fd410b3a2a694.jpg",
            "storeName": "태우네 레저",
        },
        {
            "storeId":2,
            "category":"riding",
            "title":"카약 함덕점",
            "content":"소개글 내용입니다2",
            "address": "제주시 제주도 제주읍",
            "rating": 4.7,
            "reviewCount": 9,
            "price":20000,
            "isLike":true,
            "storeImage": "https://i.pinimg.com/564x/d3/01/a7/d301a713db387daed185e8f14e4c5f97.jpg",
            "storeName": "이수네 승마",
        },
        {
            "storeId":3,
            "category":"riding",
            "title":"카약 함덕점",
            "content":"소개글 내용입니다3",
            "address": "제주시 제주도 제주읍",
            "rating": 5.0,
            "reviewCount": 19,
            "price":20000,
            "isLike":true,
            "storeImage": "https://i.pinimg.com/564x/d0/12/db/d012db7ca1e82ffe50ff0930720d7fd1.jpg",
            "storeName": "동우네 카약체험",
        },
        {
            "storeId":4,
            "category":"waterleisure",
            "title":"카약 함덕점",
            "content":"소개글 내용입니다4",
            "address": "제주시 제주도 제주읍",
            "rating": 3.7,
            "reviewCount": 26,
            "price":20000,
            "isLike":true,
            "storeImage": "https://i.pinimg.com/564x/5a/d6/02/5ad602af24d51a6773dceebc6e3080f5.jpg",
            "storeName": "민지네 ATV",
        },
        {
            "storeId":5,
            "category":"waterleisure",
            "title":"다이빙 애월점",
            "content":"소개글 내용입니다5",
            "address": "제주시 제주도 제주읍",
            "rating": 4.7,
            "reviewCount": 9,
            "price":20000,
            "isLike":true,
            "storeImage": "https://i.pinimg.com/564x/e2/dc/b6/e2dcb6e6a1342e18fa2329dc63daa422.jpg",
            "storeName": "용만이네 다이빙",
        },
        {
            "storeId":6,
            "category":"waterleisure",
            "title":"다이빙 애월점",
            "content":"소개글 내용입니다6",
            "address": "제주시 제주도 제주읍",
            "rating": 4.7,
            "reviewCount": 30,
            "price":20000,
            "isLike":true,
            "storeImage": "https://i.pinimg.com/564x/a1/72/cd/a172cdcf1760e4c562f93795ff5ca81e.jpg",
            "storeName": "채은이네 서핑",
        }
    ]
};
